// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {polaris} from '../models';
import {nodejs} from '../models';
import {jira} from '../models';
import {docker} from '../models';
import {git} from '../models';
import {terminal} from '../models';
import {gh} from '../models';

export function AppVersion():Promise<string>;

export function BackendStatus():Promise<main.BackendStatus>;

export function CancelAgent(arg1:string):Promise<void>;

export function CancelRepoWorkflowRun(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CheckForUpdate(arg1:boolean):Promise<polaris.UpdateInfo>;

export function CheckOutdatedPackages(arg1:string,arg2:string,arg3:string):Promise<Array<nodejs.OutdatedPackage>>;

export function CheckPackagesInstalled(arg1:string):Promise<boolean>;

export function CheckUnusedPackages(arg1:string,arg2:string,arg3:string):Promise<Array<nodejs.UnusedPackage>>;

export function CheckVulnerabilities(arg1:string,arg2:string,arg3:string):Promise<Array<nodejs.Vulnerability>>;

export function CloneRepository(arg1:string,arg2:string):Promise<string>;

export function CommitAgent(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CommitProject(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateJiraIssue(arg1:jira.Config,arg2:jira.CreateIssueInput):Promise<string>;

export function CreatePRForAgent(arg1:string):Promise<string>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteAutomation(arg1:string):Promise<void>;

export function DeleteCustomProvider(arg1:string):Promise<void>;

export function DeleteNotification(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DetectAgentClis():Promise<Array<main.AgentCli>>;

export function DetectDockerProject(arg1:string):Promise<docker.Project>;

export function DetectGitRemote(arg1:string):Promise<git.Remote>;

export function DetectIdes():Promise<Array<main.Ide>>;

export function DetectNodeProject(arg1:string):Promise<nodejs.Project>;

export function DetectProviderToken(arg1:string):Promise<git.ProviderToken>;

export function DetectTerminals():Promise<Array<terminal.Terminal>>;

export function DockerCapabilities():Promise<docker.Capabilities>;

export function DockerImageHistory(arg1:string):Promise<Array<docker.Layer>>;

export function FetchClaudeUsage(arg1:boolean):Promise<polaris.ClaudeUsage>;

export function FetchJiraIssueDetail(arg1:jira.Config,arg2:string):Promise<jira.IssueDetail>;

export function FetchJiraSprint(arg1:jira.Config):Promise<jira.Sprint>;

export function GetAgentDiff(arg1:string):Promise<string>;

export function GetAgentFileStatuses(arg1:string):Promise<Array<git.FileChangeStatus>>;

export function GetAgentGitState(arg1:string):Promise<git.AgentState>;

export function GetAppearanceSettings():Promise<polaris.AppearanceSettings>;

export function GetGeneralSettings():Promise<polaris.GeneralSettings>;

export function GetGhCurrentUser():Promise<string>;

export function GetNotificationSettings():Promise<polaris.NotificationSettings>;

export function GetProjectDiff(arg1:string):Promise<string>;

export function GetProjectFileStatuses(arg1:string):Promise<Array<git.FileChangeStatus>>;

export function GetProjectGitState(arg1:string):Promise<git.AgentState>;

export function GetRepoWorkflowDispatch(arg1:string,arg2:string,arg3:number):Promise<gh.WorkflowDispatchSpec>;

export function GetShortcutsSettings():Promise<polaris.ShortcutsSettings>;

export function LintDockerfile(arg1:string):Promise<Array<docker.Finding>>;

export function ListAgents(arg1:string):Promise<Array<polaris.Agent>>;

export function ListAutomationRuns(arg1:string,arg2:number):Promise<Array<polaris.AutomationRun>>;

export function ListAutomations():Promise<Array<polaris.Automation>>;

export function ListCustomProviders():Promise<Array<polaris.CustomProvider>>;

export function ListDockerBaseImages(arg1:string):Promise<Array<docker.Image>>;

export function ListJiraBoards(arg1:jira.Config):Promise<Array<jira.BoardInfo>>;

export function ListJiraIssueComments(arg1:jira.Config,arg2:string):Promise<Array<jira.Comment>>;

export function ListJiraIssueHistory(arg1:jira.Config,arg2:string):Promise<Array<jira.HistoryEntry>>;

export function ListJiraIssueTypes(arg1:jira.Config):Promise<Array<jira.IssueType>>;

export function ListNodePackages(arg1:string):Promise<Array<nodejs.Dependency>>;

export function ListNodeScripts(arg1:string):Promise<Array<nodejs.Script>>;

export function ListNodeWorkspaces(arg1:string):Promise<Array<nodejs.Workspace>>;

export function ListNotifications():Promise<Array<polaris.Notification>>;

export function ListProjectBranches(arg1:string):Promise<Array<git.BranchInfo>>;

export function ListProjectDir(arg1:string,arg2:string):Promise<Array<main.CodeEntry>>;

export function ListProjects():Promise<Array<polaris.Project>>;

export function ListRepoBranches(arg1:string,arg2:string):Promise<Array<string>>;

export function ListRepoIssues(arg1:string,arg2:string):Promise<Array<gh.Issue>>;

export function ListRepoPullRequests(arg1:string,arg2:string):Promise<Array<gh.PullRequest>>;

export function ListRepoWorkflowRuns(arg1:string,arg2:string,arg3:number):Promise<gh.WorkflowRunsPage>;

export function MarkAllNotificationsRead():Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string,arg2:string):Promise<void>;

export function ParseDockerfile(arg1:string):Promise<docker.Dockerfile>;

export function PasteClipboardImage():Promise<string>;

export function PickFiles(arg1:string):Promise<Array<string>>;

export function Ping():Promise<string>;

export function PushAgent(arg1:string,arg2:boolean):Promise<void>;

export function PushProject(arg1:string,arg2:boolean):Promise<void>;

export function ReadAgentLog(arg1:string):Promise<string>;

export function ReadAgentLogTail(arg1:string,arg2:number):Promise<Array<string>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadProjectFile(arg1:string,arg2:string):Promise<string>;

export function RerunRepoWorkflowRun(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ResetAllData():Promise<void>;

export function RespondToAgentQuestion(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunNodeCommand(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function SaveTempImage(arg1:string,arg2:string):Promise<string>;

export function ScanDockerImage(arg1:string):Promise<Array<docker.Vulnerability>>;

export function SendToAgent(arg1:string,arg2:string):Promise<void>;

export function SetAppFocused(arg1:boolean):Promise<void>;

export function SetNodeDependencyVersion(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SpawnAgent(arg1:polaris.SpawnAgentInput):Promise<polaris.Agent>;

export function StageAgentChanges(arg1:string):Promise<void>;

export function StageAgentFile(arg1:string,arg2:string):Promise<void>;

export function StageProjectChanges(arg1:string):Promise<void>;

export function StageProjectFile(arg1:string,arg2:string):Promise<void>;

export function StartNodeScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StopNodeScript(arg1:string):Promise<void>;

export function SwitchProjectBranch(arg1:string,arg2:string):Promise<void>;

export function SyncAgent(arg1:string,arg2:boolean):Promise<void>;

export function SyncProject(arg1:string,arg2:boolean):Promise<void>;

export function TransitionJiraIssue(arg1:jira.Config,arg2:string,arg3:Array<string>):Promise<void>;

export function TriggerRepoWorkflow(arg1:string,arg2:string,arg3:number,arg4:string,arg5:Record<string, string>):Promise<void>;

export function UnstageAgentChanges(arg1:string):Promise<void>;

export function UnstageAgentFile(arg1:string,arg2:string):Promise<void>;

export function UnstageProjectChanges(arg1:string):Promise<void>;

export function UnstageProjectFile(arg1:string,arg2:string):Promise<void>;

export function UpdateAppearanceSettings(arg1:polaris.AppearanceSettings):Promise<polaris.AppearanceSettings>;

export function UpdateGeneralSettings(arg1:polaris.GeneralSettings):Promise<polaris.GeneralSettings>;

export function UpdateNotificationSettings(arg1:polaris.NotificationSettings):Promise<polaris.NotificationSettings>;

export function UpdateShortcutsSettings(arg1:polaris.ShortcutsSettings):Promise<polaris.ShortcutsSettings>;

export function UpsertAgent(arg1:polaris.Agent):Promise<polaris.Agent>;

export function UpsertAutomation(arg1:polaris.Automation):Promise<polaris.Automation>;

export function UpsertCustomProvider(arg1:polaris.CustomProvider):Promise<polaris.CustomProvider>;

export function UpsertNotification(arg1:polaris.Notification):Promise<polaris.Notification>;

export function UpsertProject(arg1:polaris.Project):Promise<polaris.Project>;

export function WriteProjectFile(arg1:string,arg2:string,arg3:string):Promise<void>;
