// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {polaris} from '../models';
import {nodejs} from '../models';
import {python} from '../models';
import {tickets} from '../models';
import {docker} from '../models';
import {git} from '../models';
import {terminal} from '../models';
import {sentry} from '../models';
import {dokploy} from '../models';
import {repository} from '../models';
import {resend} from '../models';

export function AppVersion():Promise<string>;

export function BackendStatus():Promise<main.BackendStatus>;

export function CancelAgent(arg1:string):Promise<void>;

export function CancelRepoWorkflowRun(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CheckForUpdate(arg1:boolean):Promise<polaris.UpdateInfo>;

export function CheckOutdatedPackages(arg1:string,arg2:string,arg3:string):Promise<Array<nodejs.OutdatedPackage>>;

export function CheckPackagesInstalled(arg1:string):Promise<boolean>;

export function CheckPythonOutdatedPackages(arg1:string,arg2:string,arg3:string):Promise<Array<python.OutdatedPackage>>;

export function CheckPythonPackagesInstalled(arg1:string,arg2:string):Promise<boolean>;

export function CheckPythonUnusedPackages(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<python.UnusedPackage>>;

export function CheckPythonVulnerabilities(arg1:string,arg2:string,arg3:string):Promise<Array<python.Vulnerability>>;

export function CheckUnusedPackages(arg1:string,arg2:string,arg3:string):Promise<Array<nodejs.UnusedPackage>>;

export function CheckVulnerabilities(arg1:string,arg2:string,arg3:string):Promise<Array<nodejs.Vulnerability>>;

export function ClearAgentLog(arg1:string):Promise<void>;

export function CloneRepository(arg1:string,arg2:string):Promise<string>;

export function CommitAgent(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CommitProject(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function CreateJiraIssue(arg1:tickets.Config,arg2:tickets.CreateIssueInput):Promise<string>;

export function CreatePRForAgent(arg1:string):Promise<string>;

export function DeleteAgent(arg1:string):Promise<void>;

export function DeleteAutomation(arg1:string):Promise<void>;

export function DeleteCustomProvider(arg1:string):Promise<void>;

export function DeleteNotification(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DetectAgentClis():Promise<Array<main.AgentCli>>;

export function DetectAllDockerProjects(arg1:string):Promise<Array<docker.Project>>;

export function DetectAllNodeProjects(arg1:string):Promise<Array<nodejs.Project>>;

export function DetectAllPythonProjects(arg1:string):Promise<Array<python.Project>>;

export function DetectDockerProject(arg1:string):Promise<docker.Project>;

export function DetectGitRemote(arg1:string):Promise<git.Remote>;

export function DetectIdes():Promise<Array<main.Ide>>;

export function DetectNodeProject(arg1:string):Promise<nodejs.Project>;

export function DetectProviderToken(arg1:string):Promise<git.ProviderToken>;

export function DetectPythonProject(arg1:string):Promise<python.Project>;

export function DetectTerminals():Promise<Array<terminal.Terminal>>;

export function DockerCapabilities():Promise<docker.Capabilities>;

export function DockerImageHistory(arg1:string):Promise<Array<docker.Layer>>;

export function FetchClaudeModels(arg1:boolean):Promise<Array<polaris.ClaudeModel>>;

export function FetchClaudeUsage(arg1:boolean):Promise<polaris.ClaudeUsage>;

export function FetchJiraIssueDetail(arg1:tickets.Config,arg2:string):Promise<tickets.IssueDetail>;

export function FetchJiraSprint(arg1:tickets.Config):Promise<tickets.Sprint>;

export function FetchSentryIssues(arg1:sentry.Config):Promise<Array<sentry.Issue>>;

export function FetchSentryLatestEvent(arg1:sentry.Config,arg2:string):Promise<sentry.EventDetail>;

export function FireAutomation(arg1:string):Promise<void>;

export function GetAgentDefaultModels():Promise<Record<string, string>>;

export function GetAgentDiff(arg1:string):Promise<string>;

export function GetAgentFileStatuses(arg1:string):Promise<Array<git.FileChangeStatus>>;

export function GetAgentGitState(arg1:string):Promise<git.AgentState>;

export function GetAppearanceSettings():Promise<polaris.AppearanceSettings>;

export function GetDokployDashboard(arg1:dokploy.Config,arg2:Array<string>):Promise<main.DokployDashboard>;

export function GetDokployDeploymentLogs(arg1:dokploy.Config,arg2:string,arg3:number):Promise<string>;

export function GetDokployServiceLogs(arg1:dokploy.Config,arg2:dokploy.Service,arg3:number):Promise<string>;

export function GetGeneralSettings():Promise<polaris.GeneralSettings>;

export function GetGhCurrentUser():Promise<string>;

export function GetNotificationSettings():Promise<polaris.NotificationSettings>;

export function GetProjectDiff(arg1:string):Promise<string>;

export function GetProjectFileStatuses(arg1:string):Promise<Array<git.FileChangeStatus>>;

export function GetProjectGitState(arg1:string):Promise<git.AgentState>;

export function GetRepoWorkflowDispatch(arg1:string,arg2:string,arg3:number):Promise<repository.WorkflowDispatchSpec>;

export function GetShortcutsSettings():Promise<polaris.ShortcutsSettings>;

export function GetSlackConfig(arg1:string):Promise<Record<string, any>>;

export function LintDockerfile(arg1:string):Promise<Array<docker.Finding>>;

export function ListAgents(arg1:string):Promise<Array<polaris.Agent>>;

export function ListAutomationRuns(arg1:string,arg2:number):Promise<Array<polaris.AutomationRun>>;

export function ListAutomations():Promise<Array<polaris.Automation>>;

export function ListClaudeCodeSessions(arg1:string):Promise<Array<polaris.ClaudeSession>>;

export function ListCustomProviders():Promise<Array<polaris.CustomProvider>>;

export function ListDockerBaseImages(arg1:string):Promise<Array<docker.Image>>;

export function ListDokployProjectNames(arg1:dokploy.Config):Promise<Array<string>>;

export function ListJiraBoards(arg1:tickets.Config):Promise<Array<tickets.BoardInfo>>;

export function ListJiraIssueComments(arg1:tickets.Config,arg2:string):Promise<Array<tickets.Comment>>;

export function ListJiraIssueHistory(arg1:tickets.Config,arg2:string):Promise<Array<tickets.HistoryEntry>>;

export function ListJiraIssueTypes(arg1:tickets.Config):Promise<Array<tickets.IssueType>>;

export function ListNodePackages(arg1:string):Promise<Array<nodejs.Dependency>>;

export function ListNodeScripts(arg1:string):Promise<Array<nodejs.Script>>;

export function ListNodeWorkspaces(arg1:string):Promise<Array<nodejs.Workspace>>;

export function ListNotifications():Promise<Array<polaris.Notification>>;

export function ListOpencodeModels():Promise<Array<string>>;

export function ListProjectBranches(arg1:string):Promise<Array<git.BranchInfo>>;

export function ListProjectDir(arg1:string,arg2:string):Promise<Array<main.CodeEntry>>;

export function ListProjects():Promise<Array<polaris.Project>>;

export function ListPythonPackages(arg1:string,arg2:string):Promise<Array<python.Dependency>>;

export function ListPythonScripts(arg1:string):Promise<Array<python.Script>>;

export function ListPythonWorkspaces(arg1:string,arg2:string):Promise<Array<python.Workspace>>;

export function ListRepoBranches(arg1:string,arg2:string):Promise<Array<string>>;

export function ListRepoIssues(arg1:string,arg2:string):Promise<Array<repository.Issue>>;

export function ListRepoPullRequests(arg1:string,arg2:string):Promise<Array<repository.PullRequest>>;

export function ListRepoWorkflowRuns(arg1:string,arg2:string,arg3:number):Promise<repository.WorkflowRunsPage>;

export function ListResendDomains(arg1:resend.Config):Promise<Array<resend.Domain>>;

export function ListResendEmails(arg1:resend.Config,arg2:number):Promise<Array<resend.Email>>;

export function MarkAllNotificationsRead():Promise<void>;

export function MarkNotificationRead(arg1:string):Promise<void>;

export function OpenDirectory(arg1:string):Promise<string>;

export function OpenExternalURL(arg1:string):Promise<void>;

export function OpenTerminal(arg1:string,arg2:string):Promise<void>;

export function ParseDockerfile(arg1:string):Promise<docker.Dockerfile>;

export function PasteClipboardImage():Promise<string>;

export function PickFiles(arg1:string):Promise<Array<string>>;

export function Ping():Promise<string>;

export function PushAgent(arg1:string,arg2:boolean):Promise<void>;

export function PushProject(arg1:string,arg2:boolean):Promise<void>;

export function ReadAgentLog(arg1:string):Promise<string>;

export function ReadAgentLogTail(arg1:string,arg2:number):Promise<Array<string>>;

export function ReadFileBase64(arg1:string):Promise<string>;

export function ReadProjectFile(arg1:string,arg2:string):Promise<string>;

export function RerunRepoWorkflowRun(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ResetAllData():Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RespondToAgentQuestion(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RunDokployAction(arg1:dokploy.Config,arg2:dokploy.Service,arg3:string):Promise<void>;

export function RunNodeCommand(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function RunPythonCommand(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;

export function SaveSlackConfig(arg1:string,arg2:string):Promise<void>;

export function SaveTempImage(arg1:string,arg2:string):Promise<string>;

export function ScanDockerImage(arg1:string):Promise<Array<docker.Vulnerability>>;

export function SendResendEmail(arg1:resend.Config,arg2:resend.SendInput):Promise<string>;

export function SendToAgent(arg1:string,arg2:string):Promise<void>;

export function SetAgentDefaultModel(arg1:string,arg2:string):Promise<void>;

export function SetAgentModel(arg1:string,arg2:string):Promise<void>;

export function SetAppFocused(arg1:boolean):Promise<void>;

export function SetNodeDependencyVersion(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SetPythonDependencyVersion(arg1:Array<string>,arg2:string,arg3:string):Promise<void>;

export function SpawnAgent(arg1:polaris.SpawnAgentInput):Promise<polaris.Agent>;

export function StageAgentChanges(arg1:string):Promise<void>;

export function StageAgentFile(arg1:string,arg2:string):Promise<void>;

export function StageAgentFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function StageProjectChanges(arg1:string):Promise<void>;

export function StageProjectFile(arg1:string,arg2:string):Promise<void>;

export function StageProjectFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function StartNodeScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartPythonScript(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function StartShell(arg1:string):Promise<string>;

export function StopNodeScript(arg1:string):Promise<void>;

export function StopPythonScript(arg1:string):Promise<void>;

export function StopShell(arg1:string):Promise<void>;

export function SwitchProjectBranch(arg1:string,arg2:string):Promise<void>;

export function SyncAgent(arg1:string,arg2:boolean):Promise<void>;

export function SyncProject(arg1:string,arg2:boolean):Promise<void>;

export function TeleportClaudeSession(arg1:string,arg2:string):Promise<polaris.Agent>;

export function TestCustomProvider(arg1:polaris.CustomProvider):Promise<polaris.ProviderHealth>;

export function TestMessagingProvider(arg1:string,arg2:string):Promise<void>;

export function TestSlackWebhook(arg1:string):Promise<void>;

export function TransitionJiraIssue(arg1:tickets.Config,arg2:string,arg3:Array<string>):Promise<void>;

export function TriggerRepoWorkflow(arg1:string,arg2:string,arg3:number,arg4:string,arg5:Record<string, string>):Promise<void>;

export function UnstageAgentChanges(arg1:string):Promise<void>;

export function UnstageAgentFile(arg1:string,arg2:string):Promise<void>;

export function UnstageAgentFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function UnstageProjectChanges(arg1:string):Promise<void>;

export function UnstageProjectFile(arg1:string,arg2:string):Promise<void>;

export function UnstageProjectFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function UpdateAppearanceSettings(arg1:polaris.AppearanceSettings):Promise<polaris.AppearanceSettings>;

export function UpdateGeneralSettings(arg1:polaris.GeneralSettings):Promise<polaris.GeneralSettings>;

export function UpdateNotificationSettings(arg1:polaris.NotificationSettings):Promise<polaris.NotificationSettings>;

export function UpdateSentryIssueStatus(arg1:sentry.Config,arg2:string,arg3:string):Promise<void>;

export function UpdateShortcutsSettings(arg1:polaris.ShortcutsSettings):Promise<polaris.ShortcutsSettings>;

export function UpsertAgent(arg1:polaris.Agent):Promise<polaris.Agent>;

export function UpsertAutomation(arg1:polaris.Automation):Promise<polaris.Automation>;

export function UpsertCustomProvider(arg1:polaris.CustomProvider):Promise<polaris.CustomProvider>;

export function UpsertNotification(arg1:polaris.Notification):Promise<polaris.Notification>;

export function UpsertProject(arg1:polaris.Project):Promise<polaris.Project>;

export function WriteProjectFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WriteToShell(arg1:string,arg2:string):Promise<void>;
