// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppVersion() {
  return window['go']['main']['App']['AppVersion']();
}

export function ArchiveAgent(arg1) {
  return window['go']['main']['App']['ArchiveAgent'](arg1);
}

export function AssignTicketsIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['AssignTicketsIssue'](arg1, arg2, arg3);
}

export function BackendStatus() {
  return window['go']['main']['App']['BackendStatus']();
}

export function CancelAgent(arg1) {
  return window['go']['main']['App']['CancelAgent'](arg1);
}

export function CancelRepoWorkflowRun(arg1, arg2, arg3) {
  return window['go']['main']['App']['CancelRepoWorkflowRun'](arg1, arg2, arg3);
}

export function CheckForUpdate(arg1) {
  return window['go']['main']['App']['CheckForUpdate'](arg1);
}

export function CheckOutdatedPackages(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckOutdatedPackages'](arg1, arg2, arg3);
}

export function CheckPackagesInstalled(arg1) {
  return window['go']['main']['App']['CheckPackagesInstalled'](arg1);
}

export function CheckPythonOutdatedPackages(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckPythonOutdatedPackages'](arg1, arg2, arg3);
}

export function CheckPythonPackagesInstalled(arg1, arg2) {
  return window['go']['main']['App']['CheckPythonPackagesInstalled'](arg1, arg2);
}

export function CheckPythonUnusedPackages(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CheckPythonUnusedPackages'](arg1, arg2, arg3, arg4);
}

export function CheckPythonVulnerabilities(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckPythonVulnerabilities'](arg1, arg2, arg3);
}

export function CheckUnusedPackages(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckUnusedPackages'](arg1, arg2, arg3);
}

export function CheckVulnerabilities(arg1, arg2, arg3) {
  return window['go']['main']['App']['CheckVulnerabilities'](arg1, arg2, arg3);
}

export function ClearAgentLog(arg1) {
  return window['go']['main']['App']['ClearAgentLog'](arg1);
}

export function CloneRepository(arg1, arg2) {
  return window['go']['main']['App']['CloneRepository'](arg1, arg2);
}

export function CommitAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitAgent'](arg1, arg2, arg3);
}

export function CommitProject(arg1, arg2, arg3) {
  return window['go']['main']['App']['CommitProject'](arg1, arg2, arg3);
}

export function CreatePRForAgent(arg1) {
  return window['go']['main']['App']['CreatePRForAgent'](arg1);
}

export function CreateTicketsIssue(arg1, arg2) {
  return window['go']['main']['App']['CreateTicketsIssue'](arg1, arg2);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteAutomation(arg1) {
  return window['go']['main']['App']['DeleteAutomation'](arg1);
}

export function DeleteCustomProvider(arg1) {
  return window['go']['main']['App']['DeleteCustomProvider'](arg1);
}

export function DeleteNotification(arg1) {
  return window['go']['main']['App']['DeleteNotification'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DetectAgentClis() {
  return window['go']['main']['App']['DetectAgentClis']();
}

export function DetectAllDockerProjects(arg1) {
  return window['go']['main']['App']['DetectAllDockerProjects'](arg1);
}

export function DetectAllNodeProjects(arg1) {
  return window['go']['main']['App']['DetectAllNodeProjects'](arg1);
}

export function DetectAllPythonProjects(arg1) {
  return window['go']['main']['App']['DetectAllPythonProjects'](arg1);
}

export function DetectDockerProject(arg1) {
  return window['go']['main']['App']['DetectDockerProject'](arg1);
}

export function DetectGitRemote(arg1) {
  return window['go']['main']['App']['DetectGitRemote'](arg1);
}

export function DetectIdes() {
  return window['go']['main']['App']['DetectIdes']();
}

export function DetectNodeProject(arg1) {
  return window['go']['main']['App']['DetectNodeProject'](arg1);
}

export function DetectProviderToken(arg1) {
  return window['go']['main']['App']['DetectProviderToken'](arg1);
}

export function DetectPythonProject(arg1) {
  return window['go']['main']['App']['DetectPythonProject'](arg1);
}

export function DetectTerminals() {
  return window['go']['main']['App']['DetectTerminals']();
}

export function DiscardAgentFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscardAgentFile'](arg1, arg2, arg3);
}

export function DiscardAgentFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['DiscardAgentFiles'](arg1, arg2, arg3);
}

export function DockerCapabilities() {
  return window['go']['main']['App']['DockerCapabilities']();
}

export function DockerImageHistory(arg1) {
  return window['go']['main']['App']['DockerImageHistory'](arg1);
}

export function FetchClaudeModels(arg1) {
  return window['go']['main']['App']['FetchClaudeModels'](arg1);
}

export function FetchClaudeUsage(arg1) {
  return window['go']['main']['App']['FetchClaudeUsage'](arg1);
}

export function FetchCursorUsage(arg1) {
  return window['go']['main']['App']['FetchCursorUsage'](arg1);
}

export function FetchSentryIssues(arg1) {
  return window['go']['main']['App']['FetchSentryIssues'](arg1);
}

export function FetchSentryLatestEvent(arg1, arg2) {
  return window['go']['main']['App']['FetchSentryLatestEvent'](arg1, arg2);
}

export function FetchTicketsIssueDetail(arg1, arg2) {
  return window['go']['main']['App']['FetchTicketsIssueDetail'](arg1, arg2);
}

export function FetchTicketsSprint(arg1) {
  return window['go']['main']['App']['FetchTicketsSprint'](arg1);
}

export function FireAutomation(arg1) {
  return window['go']['main']['App']['FireAutomation'](arg1);
}

export function GenerateCommitMessageForAgent(arg1) {
  return window['go']['main']['App']['GenerateCommitMessageForAgent'](arg1);
}

export function GetAgentDefaultModels() {
  return window['go']['main']['App']['GetAgentDefaultModels']();
}

export function GetAgentDiff(arg1) {
  return window['go']['main']['App']['GetAgentDiff'](arg1);
}

export function GetAgentFileStatuses(arg1) {
  return window['go']['main']['App']['GetAgentFileStatuses'](arg1);
}

export function GetAgentGitState(arg1) {
  return window['go']['main']['App']['GetAgentGitState'](arg1);
}

export function GetAppearanceSettings() {
  return window['go']['main']['App']['GetAppearanceSettings']();
}

export function GetDokployDashboard(arg1, arg2) {
  return window['go']['main']['App']['GetDokployDashboard'](arg1, arg2);
}

export function GetDokployDeploymentLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDokployDeploymentLogs'](arg1, arg2, arg3);
}

export function GetDokployServiceLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDokployServiceLogs'](arg1, arg2, arg3);
}

export function GetGeneralSettings() {
  return window['go']['main']['App']['GetGeneralSettings']();
}

export function GetNotificationSettings() {
  return window['go']['main']['App']['GetNotificationSettings']();
}

export function GetProjectDiff(arg1) {
  return window['go']['main']['App']['GetProjectDiff'](arg1);
}

export function GetProjectFileStatuses(arg1) {
  return window['go']['main']['App']['GetProjectFileStatuses'](arg1);
}

export function GetProjectGitState(arg1) {
  return window['go']['main']['App']['GetProjectGitState'](arg1);
}

export function GetRepoWorkflowDispatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetRepoWorkflowDispatch'](arg1, arg2, arg3);
}

export function GetRepositoryCurrentUser() {
  return window['go']['main']['App']['GetRepositoryCurrentUser']();
}

export function GetShortcutsSettings() {
  return window['go']['main']['App']['GetShortcutsSettings']();
}

export function GetSlackConfig(arg1) {
  return window['go']['main']['App']['GetSlackConfig'](arg1);
}

export function GetTicketsCurrentUser(arg1) {
  return window['go']['main']['App']['GetTicketsCurrentUser'](arg1);
}

export function LintDockerfile(arg1) {
  return window['go']['main']['App']['LintDockerfile'](arg1);
}

export function ListAgents(arg1) {
  return window['go']['main']['App']['ListAgents'](arg1);
}

export function ListAutomationRuns(arg1, arg2) {
  return window['go']['main']['App']['ListAutomationRuns'](arg1, arg2);
}

export function ListAutomations() {
  return window['go']['main']['App']['ListAutomations']();
}

export function ListClaudeCodeSessions(arg1) {
  return window['go']['main']['App']['ListClaudeCodeSessions'](arg1);
}

export function ListCustomProviders() {
  return window['go']['main']['App']['ListCustomProviders']();
}

export function ListDockerBaseImages(arg1) {
  return window['go']['main']['App']['ListDockerBaseImages'](arg1);
}

export function ListDokployProjectNames(arg1) {
  return window['go']['main']['App']['ListDokployProjectNames'](arg1);
}

export function ListNodePackages(arg1) {
  return window['go']['main']['App']['ListNodePackages'](arg1);
}

export function ListNodeScripts(arg1) {
  return window['go']['main']['App']['ListNodeScripts'](arg1);
}

export function ListNodeWorkspaces(arg1) {
  return window['go']['main']['App']['ListNodeWorkspaces'](arg1);
}

export function ListNotifications() {
  return window['go']['main']['App']['ListNotifications']();
}

export function ListOpencodeModels() {
  return window['go']['main']['App']['ListOpencodeModels']();
}

export function ListProjectBranches(arg1) {
  return window['go']['main']['App']['ListProjectBranches'](arg1);
}

export function ListProjectDir(arg1, arg2) {
  return window['go']['main']['App']['ListProjectDir'](arg1, arg2);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListPythonPackages(arg1, arg2) {
  return window['go']['main']['App']['ListPythonPackages'](arg1, arg2);
}

export function ListPythonScripts(arg1) {
  return window['go']['main']['App']['ListPythonScripts'](arg1);
}

export function ListPythonWorkspaces(arg1, arg2) {
  return window['go']['main']['App']['ListPythonWorkspaces'](arg1, arg2);
}

export function ListRepoBranches(arg1, arg2) {
  return window['go']['main']['App']['ListRepoBranches'](arg1, arg2);
}

export function ListRepoIssues(arg1, arg2) {
  return window['go']['main']['App']['ListRepoIssues'](arg1, arg2);
}

export function ListRepoPullRequests(arg1, arg2) {
  return window['go']['main']['App']['ListRepoPullRequests'](arg1, arg2);
}

export function ListRepoWorkflowRuns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRepoWorkflowRuns'](arg1, arg2, arg3);
}

export function ListResendDomains(arg1) {
  return window['go']['main']['App']['ListResendDomains'](arg1);
}

export function ListResendEmails(arg1, arg2) {
  return window['go']['main']['App']['ListResendEmails'](arg1, arg2);
}

export function ListTicketsBoards(arg1) {
  return window['go']['main']['App']['ListTicketsBoards'](arg1);
}

export function ListTicketsIssueComments(arg1, arg2) {
  return window['go']['main']['App']['ListTicketsIssueComments'](arg1, arg2);
}

export function ListTicketsIssueHistory(arg1, arg2) {
  return window['go']['main']['App']['ListTicketsIssueHistory'](arg1, arg2);
}

export function ListTicketsIssueTypes(arg1) {
  return window['go']['main']['App']['ListTicketsIssueTypes'](arg1);
}

export function MarkAllNotificationsRead() {
  return window['go']['main']['App']['MarkAllNotificationsRead']();
}

export function MarkNotificationRead(arg1) {
  return window['go']['main']['App']['MarkNotificationRead'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['main']['App']['OpenDirectory'](arg1);
}

export function OpenExternalURL(arg1) {
  return window['go']['main']['App']['OpenExternalURL'](arg1);
}

export function OpenInIde(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['OpenInIde'](arg1, arg2, arg3, arg4);
}

export function OpenTerminal(arg1, arg2) {
  return window['go']['main']['App']['OpenTerminal'](arg1, arg2);
}

export function ParseDockerfile(arg1) {
  return window['go']['main']['App']['ParseDockerfile'](arg1);
}

export function PasteClipboardImage() {
  return window['go']['main']['App']['PasteClipboardImage']();
}

export function PickFiles(arg1) {
  return window['go']['main']['App']['PickFiles'](arg1);
}

export function Ping() {
  return window['go']['main']['App']['Ping']();
}

export function PushAgent(arg1, arg2) {
  return window['go']['main']['App']['PushAgent'](arg1, arg2);
}

export function PushProject(arg1, arg2) {
  return window['go']['main']['App']['PushProject'](arg1, arg2);
}

export function ReadAgentLog(arg1) {
  return window['go']['main']['App']['ReadAgentLog'](arg1);
}

export function ReadFileBase64(arg1) {
  return window['go']['main']['App']['ReadFileBase64'](arg1);
}

export function ReadProjectFile(arg1, arg2) {
  return window['go']['main']['App']['ReadProjectFile'](arg1, arg2);
}

export function RerunRepoWorkflowRun(arg1, arg2, arg3) {
  return window['go']['main']['App']['RerunRepoWorkflowRun'](arg1, arg2, arg3);
}

export function ResetAllData() {
  return window['go']['main']['App']['ResetAllData']();
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function RespondToAgentQuestion(arg1, arg2, arg3) {
  return window['go']['main']['App']['RespondToAgentQuestion'](arg1, arg2, arg3);
}

export function RunDokployAction(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunDokployAction'](arg1, arg2, arg3);
}

export function RunNodeCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunNodeCommand'](arg1, arg2, arg3, arg4);
}

export function RunPythonCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RunPythonCommand'](arg1, arg2, arg3, arg4);
}

export function SaveSlackConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveSlackConfig'](arg1, arg2);
}

export function SaveTempImage(arg1, arg2) {
  return window['go']['main']['App']['SaveTempImage'](arg1, arg2);
}

export function ScanDockerImage(arg1) {
  return window['go']['main']['App']['ScanDockerImage'](arg1);
}

export function SendResendEmail(arg1, arg2) {
  return window['go']['main']['App']['SendResendEmail'](arg1, arg2);
}

export function SendToAgent(arg1, arg2) {
  return window['go']['main']['App']['SendToAgent'](arg1, arg2);
}

export function SetAgentDefaultModel(arg1, arg2) {
  return window['go']['main']['App']['SetAgentDefaultModel'](arg1, arg2);
}

export function SetAgentModel(arg1, arg2) {
  return window['go']['main']['App']['SetAgentModel'](arg1, arg2);
}

export function SetAppFocused(arg1) {
  return window['go']['main']['App']['SetAppFocused'](arg1);
}

export function SetNodeDependencyVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetNodeDependencyVersion'](arg1, arg2, arg3);
}

export function SetPythonDependencyVersion(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetPythonDependencyVersion'](arg1, arg2, arg3);
}

export function SpawnAgent(arg1) {
  return window['go']['main']['App']['SpawnAgent'](arg1);
}

export function StageAgentChanges(arg1) {
  return window['go']['main']['App']['StageAgentChanges'](arg1);
}

export function StageAgentFile(arg1, arg2) {
  return window['go']['main']['App']['StageAgentFile'](arg1, arg2);
}

export function StageAgentFiles(arg1, arg2) {
  return window['go']['main']['App']['StageAgentFiles'](arg1, arg2);
}

export function StageProjectChanges(arg1) {
  return window['go']['main']['App']['StageProjectChanges'](arg1);
}

export function StageProjectFile(arg1, arg2) {
  return window['go']['main']['App']['StageProjectFile'](arg1, arg2);
}

export function StageProjectFiles(arg1, arg2) {
  return window['go']['main']['App']['StageProjectFiles'](arg1, arg2);
}

export function StartNodeScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartNodeScript'](arg1, arg2, arg3, arg4);
}

export function StartPythonScript(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPythonScript'](arg1, arg2, arg3, arg4);
}

export function StartShell(arg1) {
  return window['go']['main']['App']['StartShell'](arg1);
}

export function StopNodeScript(arg1) {
  return window['go']['main']['App']['StopNodeScript'](arg1);
}

export function StopPythonScript(arg1) {
  return window['go']['main']['App']['StopPythonScript'](arg1);
}

export function StopShell(arg1) {
  return window['go']['main']['App']['StopShell'](arg1);
}

export function SwitchProjectBranch(arg1, arg2) {
  return window['go']['main']['App']['SwitchProjectBranch'](arg1, arg2);
}

export function SyncAgent(arg1, arg2) {
  return window['go']['main']['App']['SyncAgent'](arg1, arg2);
}

export function SyncProject(arg1, arg2) {
  return window['go']['main']['App']['SyncProject'](arg1, arg2);
}

export function TeleportClaudeSession(arg1, arg2) {
  return window['go']['main']['App']['TeleportClaudeSession'](arg1, arg2);
}

export function TestCustomProvider(arg1) {
  return window['go']['main']['App']['TestCustomProvider'](arg1);
}

export function TestMessagingProvider(arg1, arg2) {
  return window['go']['main']['App']['TestMessagingProvider'](arg1, arg2);
}

export function TestSlackWebhook(arg1) {
  return window['go']['main']['App']['TestSlackWebhook'](arg1);
}

export function TransitionTicketsIssue(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransitionTicketsIssue'](arg1, arg2, arg3);
}

export function TriggerRepoWorkflow(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['TriggerRepoWorkflow'](arg1, arg2, arg3, arg4, arg5);
}

export function UnstageAgentChanges(arg1) {
  return window['go']['main']['App']['UnstageAgentChanges'](arg1);
}

export function UnstageAgentFile(arg1, arg2) {
  return window['go']['main']['App']['UnstageAgentFile'](arg1, arg2);
}

export function UnstageAgentFiles(arg1, arg2) {
  return window['go']['main']['App']['UnstageAgentFiles'](arg1, arg2);
}

export function UnstageProjectChanges(arg1) {
  return window['go']['main']['App']['UnstageProjectChanges'](arg1);
}

export function UnstageProjectFile(arg1, arg2) {
  return window['go']['main']['App']['UnstageProjectFile'](arg1, arg2);
}

export function UnstageProjectFiles(arg1, arg2) {
  return window['go']['main']['App']['UnstageProjectFiles'](arg1, arg2);
}

export function UpdateAppearanceSettings(arg1) {
  return window['go']['main']['App']['UpdateAppearanceSettings'](arg1);
}

export function UpdateGeneralSettings(arg1) {
  return window['go']['main']['App']['UpdateGeneralSettings'](arg1);
}

export function UpdateNotificationSettings(arg1) {
  return window['go']['main']['App']['UpdateNotificationSettings'](arg1);
}

export function UpdateSentryIssueStatus(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSentryIssueStatus'](arg1, arg2, arg3);
}

export function UpdateShortcutsSettings(arg1) {
  return window['go']['main']['App']['UpdateShortcutsSettings'](arg1);
}

export function UpsertAgent(arg1) {
  return window['go']['main']['App']['UpsertAgent'](arg1);
}

export function UpsertAutomation(arg1) {
  return window['go']['main']['App']['UpsertAutomation'](arg1);
}

export function UpsertCustomProvider(arg1) {
  return window['go']['main']['App']['UpsertCustomProvider'](arg1);
}

export function UpsertNotification(arg1) {
  return window['go']['main']['App']['UpsertNotification'](arg1);
}

export function UpsertProject(arg1) {
  return window['go']['main']['App']['UpsertProject'](arg1);
}

export function WriteProjectFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteProjectFile'](arg1, arg2, arg3);
}

export function WriteToShell(arg1, arg2) {
  return window['go']['main']['App']['WriteToShell'](arg1, arg2);
}
