package polaris

import (
	"encoding/json"
	"errors"
	"sync"
	"time"

	"github.com/KevinBonnoron/polaris/internal/store/dokploystore"
	"github.com/KevinBonnoron/polaris/internal/store/repositorystore"
	"github.com/KevinBonnoron/polaris/internal/store/sentrystore"
	"github.com/KevinBonnoron/polaris/internal/store/ticketsstore"
)

// IntegrationConfig holds the per-plugin settings for a single integration
// connected to a project. The shape is intentionally untyped: each plugin owns
// its own schema (defined client-side in the integration catalog) and is
// responsible for validating its own fields.
type IntegrationConfig map[string]any

type Project struct {
	ID           string                       `json:"id"`
	Name         string                       `json:"name"`
	Color        string                       `json:"color"`
	Path         string                       `json:"path"`
	Logo         string                       `json:"logo"`
	Integrations map[string]IntegrationConfig `json:"integrations"`
	// IsolatedDefault is the project-level default for new agents: when true,
	// the runner spawns the agent into a fresh git worktree on a generated
	// branch; when false, the agent works on the current branch in place.
	IsolatedDefault bool `json:"isolatedDefault"`
	// BranchPrefix is the prefix prepended to auto-generated branch names
	// when IsolatedDefault is on (e.g. "polaris/", "feat/"). Used only for
	// manual spawns — automation triggers carry their own branch name.
	BranchPrefix string `json:"branchPrefix"`
	// HasGit is computed at read time from the project path. Not persisted —
	// reflects the live filesystem so it stays correct after `git init` or
	// directory moves without requiring a manual refresh.
	HasGit bool `json:"hasGit"`
}

type Agent struct {
	ID        string `json:"id"`
	ProjectID string `json:"projectId"`
	Kind      string `json:"kind"`
	// Source is "manual" (default) when the user spawned the agent from the
	// UI, or "automation" when an Automation rule triggered the run.
	Source string `json:"source"`
	// Summary is a short description of the agent's task, generated by the CLI
	// after the first turn (e.g. claude's `summary` of the user's request).
	// Empty until the first turn produces text.
	Summary   string `json:"summary"`
	Status    string `json:"status"`
	StartedAt int64  `json:"startedAt"`
	UpdatedAt int64  `json:"updatedAt"`
	// PID is the OS process id of the running agent subprocess, persisted so
	// that startup recovery (RecoverInterruptedAgents) can tell a genuinely
	// dead agent from one still running in another live app instance sharing
	// the same database. 0 when no subprocess is attached.
	PID       int    `json:"-"`
	SessionID string `json:"sessionId"`
	// Model is the CLI model chosen at spawn time. Needed for deferred-start
	// agents (created with empty task) so the first Send can pass it to the
	// initial spawn command.
	Model string `json:"model,omitempty"`
	// ProviderID is set when the agent runs against a user-defined custom
	// provider (Kind == "opencode"). It points back to the CustomProvider so
	// the UI can resolve the provider's name/colour for display.
	ProviderID string `json:"providerId,omitempty"`
	// Tokens is the per-category usage accumulated across the agent's turns. The
	// total is derived (Tokens.Total()) rather than stored, so the UI can show
	// the breakdown and explain why a total is large (cache re-reads of the
	// fixed context usually dominate the actual new work).
	Tokens        TokenUsage `json:"tokens"`
	CostUSD       float64    `json:"costUsd"`
	FilesModified int        `json:"filesModified"`
	ToolsUsed     int        `json:"toolsUsed"`
	// Worktree carries the git-isolation details when the agent runs on a
	// dedicated branch inside its own worktree (ticket-triggered or manually
	// isolated spawns). Zero value when the agent worked in the project root.
	Worktree Worktree `json:"worktree"`
	// PendingQuestion holds an unanswered AskUserQuestion tool call. Persisted
	// so the choices survive a closed modal or an app restart mid-question.
	// nil when no question is pending.
	PendingQuestion *PendingQuestion `json:"pendingQuestion,omitempty"`
	// AllowedTools restricts which claude-code tools are injected into the
	// system prompt. Empty means all tools (no restriction). Only honoured
	// for the claude-code kind; other backends manage their own tool lists.
	AllowedTools []string `json:"allowedTools,omitempty"`
}

// TokenUsage breaks an agent's token consumption into its categories. The total
// is derived via Total() rather than stored separately, since the categories
// always sum to it. cacheRead (the fixed context replayed each turn) usually
// dominates the few "new" input/output tokens.
type TokenUsage struct {
	Input         int `json:"input"`
	Output        int `json:"output"`
	CacheCreation int `json:"cacheCreation"`
	CacheRead     int `json:"cacheRead"`
}

// Total is the sum of all token categories.
func (t TokenUsage) Total() int {
	return t.Input + t.Output + t.CacheCreation + t.CacheRead
}

// Add returns the element-wise sum of two usages.
func (t TokenUsage) Add(o TokenUsage) TokenUsage {
	return TokenUsage{
		Input:         t.Input + o.Input,
		Output:        t.Output + o.Output,
		CacheCreation: t.CacheCreation + o.CacheCreation,
		CacheRead:     t.CacheRead + o.CacheRead,
	}
}

type DayStat struct {
	Date     string  `json:"date"`
	Sessions int     `json:"sessions"`
	Tokens   int64   `json:"tokens"`
	CostUsd  float64 `json:"costUsd"`
}

type KindStat struct {
	Kind     string `json:"kind"`
	Sessions int    `json:"sessions"`
	Tokens   int64  `json:"tokens"`
}

type ModelStat struct {
	Model    string `json:"model"`
	Sessions int    `json:"sessions"`
	Tokens   int64  `json:"tokens"`
}

type DashboardStats struct {
	TotalSessions       int         `json:"totalSessions"`
	AvgTokensPerSession float64     `json:"avgTokensPerSession"`
	TotalTokens         int64       `json:"totalTokens"`
	AvgCostUsd          float64     `json:"avgCostUsd"`
	TotalCostUsd        float64     `json:"totalCostUsd"`
	AvgDurationSec      float64     `json:"avgDurationSec"`
	ByDay               []DayStat   `json:"byDay"`
	ByKind              []KindStat  `json:"byKind"`
	ByModel             []ModelStat `json:"byModel"`
}

// Worktree groups the git-isolation fields of an Agent, populated when the
// agent runs on a dedicated branch inside its own worktree.
type Worktree struct {
	Branch string `json:"branch,omitempty"`
	Path   string `json:"path,omitempty"`
	// IssueKey carries the originating ticket (e.g. "ABC-123") so the PR title
	// and follow-up actions can reference it.
	IssueKey string `json:"issueKey,omitempty"`
	// PRURL is set once CreatePRForAgent successfully opened a pull request.
	PRURL string `json:"prUrl,omitempty"`
	// BaseCommit is the HEAD SHA recorded at spawn time for non-isolated agents.
	// Used by PromoteAgentToWorktree to scope the diff to only this agent's work.
	BaseCommit string `json:"baseCommit,omitempty"`
	// BaseTree is the tree SHA of the full working tree (tracked + untracked)
	// captured at spawn time for non-isolated agents. The agent's changes are
	// derived as the delta between this snapshot and the current working tree,
	// which captures shell-driven edits the log never records. Empty for agents
	// spawned before snapshots existed; callers then fall back to log scoping.
	BaseTree string `json:"baseTree,omitempty"`
}

// PendingQuestion is an AskUserQuestion tool call awaiting the user's answer.
type PendingQuestion struct {
	// ToolUseID is the tool_use id of the call, needed to route the answer back
	// as a tool_result.
	ToolUseID string `json:"toolUseId,omitempty"`
	// Input is the raw tool input (the questions payload) shown to the user.
	Input json.RawMessage `json:"input,omitempty"`
}

type CustomProvider struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Color    string   `json:"color"`
	Icon     string   `json:"icon"`
	Endpoint string   `json:"endpoint"`
	APIKey   string   `json:"apiKey"`
	APIType  string   `json:"apiType"`
	Models   []string `json:"models"`
}

// NotificationSeverity tags every notification with how concerning it is.
// The frontend uses it for tone/colour and (eventually) per-severity
// settings. Adding a value requires a matching entry in src/db/types.ts.
type NotificationSeverity string

const (
	SeverityInfo    NotificationSeverity = "info"
	SeveritySuccess NotificationSeverity = "success"
	SeverityWarning NotificationSeverity = "warning"
	SeverityError   NotificationSeverity = "error"
)

// NotificationType discriminates the source of the notification. Each value
// determines the shape of Payload (see Agent/Automation/User payload types).
type NotificationType string

const (
	NotifTypeAgent      NotificationType = "agent"
	NotifTypeAutomation NotificationType = "automation"
	NotifTypeUser       NotificationType = "user"
)

// AgentEvent narrows what happened on an agent-typed notification. Stored
// inside the agent payload, not at the top level, because automation/user
// notifications don't have an equivalent.
type AgentEvent string

const (
	AgentEventWaiting   AgentEvent = "waiting"
	AgentEventCompleted AgentEvent = "completed"
)

// AgentNotificationPayload is the JSON shape persisted in payloadJson when
// Type == NotifTypeAgent.
type AgentNotificationPayload struct {
	AgentID string     `json:"agentId"`
	Event   AgentEvent `json:"event"`
}

// AutomationNotificationPayload is the JSON shape persisted in payloadJson
// when Type == NotifTypeAutomation.
type AutomationNotificationPayload struct {
	AutomationID string `json:"automationId,omitempty"`
}

type Notification struct {
	ID        string               `json:"id"`
	ProjectID string               `json:"projectId"`
	Type      NotificationType     `json:"type"`
	Severity  NotificationSeverity `json:"severity"`
	Title     string               `json:"title"`
	Payload   map[string]any       `json:"payload,omitempty"`
	CreatedAt int64                `json:"createdAt"`
	Read      bool                 `json:"read"`
}

// AgentID is a convenience accessor for payload["agentId"] when Type=agent.
// Returns "" when the notification isn't agent-typed or the field is absent.
func (n Notification) AgentID() string {
	if n.Type != NotifTypeAgent || n.Payload == nil {
		return ""
	}
	if v, ok := n.Payload["agentId"].(string); ok {
		return v
	}
	return ""
}

// NotificationEventFlags toggles in-app and OS surfacing per category. A
// flag set to false drops the notification entirely (not persisted, no OS
// toast). The agent flags (Waiting/Completed/Errored/Started) gate
// agent-typed notifications by AgentEvent + severity; Automation and User
// gate everything emitted under their respective NotificationType.
type NotificationEventFlags struct {
	Waiting    bool `json:"waiting"`
	Completed  bool `json:"completed"`
	Errored    bool `json:"errored"`
	Started    bool `json:"started"`
	Automation bool `json:"automation"`
	User       bool `json:"user"`
}

// NotificationSettings is the user-tunable delivery policy applied at the
// service boundary before any notification is persisted or pushed to the OS.
type NotificationSettings struct {
	OSEnabled  bool                   `json:"osEnabled"`
	Sound      string                 `json:"sound"`
	SilenceAll bool                   `json:"silenceAll"`
	Events     NotificationEventFlags `json:"events"`
}

// DefaultNotificationSettings is what new installs see and what we fall back
// to when a row is missing or partially decoded.
func DefaultNotificationSettings() NotificationSettings {
	return NotificationSettings{
		OSEnabled:  true,
		Sound:      "default",
		SilenceAll: false,
		Events: NotificationEventFlags{
			Waiting:    true,
			Completed:  true,
			Errored:    true,
			Started:    false,
			Automation: true,
			User:       true,
		},
	}
}

type CustomTheme struct {
	Key    string            `json:"key"`
	Name   string            `json:"name"`
	Mode   string            `json:"mode"`
	Colors map[string]string `json:"colors"`
}

type AppearanceSettings struct {
	Theme               string        `json:"theme"`
	ThinkingStyle       string        `json:"thinkingStyle"`
	ThinkingStyleAccent bool          `json:"thinkingStyleAccent"`
	CardAnimationStyle  string        `json:"cardAnimationStyle"`
	CustomThemes        []CustomTheme `json:"customThemes"`
	StatusBarBlocks     []string      `json:"statusBarBlocks"`
	GitChangesViewMode  string        `json:"gitChangesViewMode"`
}

func DefaultAppearanceSettings() AppearanceSettings {
	return AppearanceSettings{
		Theme:              "classic-dark",
		ThinkingStyle:      "dots",
		CardAnimationStyle: "pulse",
		CustomThemes:       []CustomTheme{},
		StatusBarBlocks:    []string{"model", "tools", "tokens", "tools-used", "cost"},
		GitChangesViewMode: "list",
	}
}

type ShortcutBinding struct {
	Key  string `json:"key"`
	Meta bool   `json:"meta"`
}

type ShortcutsSettings struct {
	OpenPalette    ShortcutBinding `json:"openPalette"`
	SwitchProject  ShortcutBinding `json:"switchProject"`
	AddProject     ShortcutBinding `json:"addProject"`
	NewAgent       ShortcutBinding `json:"newAgent"`
	ToggleSidebar  ShortcutBinding `json:"toggleSidebar"`
	ToggleTerminal ShortcutBinding `json:"toggleTerminal"`
	CloseModal     ShortcutBinding `json:"closeModal"`
}

func DefaultShortcutsSettings() ShortcutsSettings {
	return ShortcutsSettings{
		OpenPalette:    ShortcutBinding{Key: "k", Meta: true},
		SwitchProject:  ShortcutBinding{Key: "p", Meta: true},
		AddProject:     ShortcutBinding{Key: "o", Meta: true},
		NewAgent:       ShortcutBinding{Key: "n", Meta: true},
		ToggleSidebar:  ShortcutBinding{Key: "b", Meta: true},
		ToggleTerminal: ShortcutBinding{Key: "j", Meta: true},
		CloseModal:     ShortcutBinding{Key: "Escape", Meta: false},
	}
}

// GeneralSettings groups misc app-wide preferences that don't belong to a
// more specific category. When AutoResumeSessions is true, agents found in
// an in-flight state at startup (working/waiting) are auto-resumed with a
// neutral continuation prompt instead of being marked as errored.
type GeneralSettings struct {
	AutoResumeSessions bool   `json:"autoResumeSessions"`
	IdeId              string `json:"ideId,omitempty"`
	IdeCmd             string `json:"ideCmd,omitempty"`
	// AgentCloseAction controls what happens to an agent session when the user
	// closes it after shipping all changes. "archive" (default) keeps the
	// session visible with an archived status; "delete" removes it entirely.
	AgentCloseAction string `json:"agentCloseAction,omitempty"`
}

func DefaultGeneralSettings() GeneralSettings {
	return GeneralSettings{
		AutoResumeSessions: false,
	}
}

// AutomationTrigger is the discriminated payload describing what conditions
// fire an automation. The wire format is JSON so the frontend can evolve the
// shape without forcing a Go-side migration on every change.
type AutomationTrigger struct {
	// Kind is one of: "tickets.transition", "repository.pr_opened",
	// "repository.pr_comment", "repository.pr_approved",
	// "repository.pr_build_failed", "repository.pr_build_success",
	// "repository.issue_assigned", "sentry.new_issue",
	// "dokploy.deployment_failed", "dokploy.deployment_succeeded".
	Kind string `json:"kind"`
	// FromStatusIDs is the set of source statuses accepted ([] = any). For
	// "tickets.transition".
	FromStatusIDs []string `json:"fromStatusIds,omitempty"`
	// ToStatusID is the destination status (required for tickets.transition).
	ToStatusID string `json:"toStatusId,omitempty"`
	// IncludeDrafts, when true, lets repository.pr_opened fire for draft PRs.
	IncludeDrafts bool `json:"includeDrafts,omitempty"`
	// AuthorFilter restricts repository.pr_opened to a specific GitHub login.
	// Empty means any author.
	AuthorFilter string `json:"authorFilter,omitempty"`
	// MinLevel is the minimum Sentry severity that fires sentry.new_issue
	// ("warning" | "error" | "fatal"). Empty means any level.
	MinLevel string `json:"minLevel,omitempty"`
}

// AutomationAction is the discriminated payload describing one action to run
// when the trigger fires. Multiple actions execute in declaration order; a
// failing action only logs and does not halt the chain.
type AutomationAction struct {
	// Kind is one of: "spawn_agent", "resume_pr_agent", "tickets_transition", "notification", "send_email", "send_message", "trigger_workflow".
	Kind string `json:"kind"`

	// spawn_agent fields
	AgentKind    string `json:"agentKind,omitempty"`
	Model        string `json:"model,omitempty"`
	TaskTemplate string `json:"taskTemplate,omitempty"`

	// tickets_transition fields. TicketIssueKey is a template (e.g. "{{key}}");
	// empty means "use the issue key from the trigger context", which for
	// repository triggers is auto-extracted from the branch or PR title.
	TicketIssueKey   string `json:"ticketsIssueKey,omitempty"`
	TicketToStatusID string `json:"ticketsToStatusId,omitempty"`

	// notification fields
	NotifyTitle string `json:"notifyTitle,omitempty"` // template
	NotifyKind  string `json:"notifyKind,omitempty"`  // "info" (default) | "warning" | "error"

	// send_email fields (requires the project's Resend integration to be configured)
	EmailTo      string `json:"emailTo,omitempty"`      // template
	EmailSubject string `json:"emailSubject,omitempty"` // template
	EmailBody    string `json:"emailBody,omitempty"`    // template, sent as plain text

	// send_message fields (requires a slack/discord/telegram integration)
	MessageProvider string `json:"messageProvider,omitempty"` // "slack" | "discord" | "telegram"
	MessageTitle    string `json:"messageTitle,omitempty"`    // template
	MessageBody     string `json:"messageBody,omitempty"`     // template

	// trigger_workflow fields (requires a repository integration)
	WorkflowFile   string `json:"workflowFile,omitempty"`   // workflow filename, e.g. "deploy.yml"; supports templates
	WorkflowRef    string `json:"workflowRef,omitempty"`    // branch/tag ref; supports templates
	WorkflowInputs string `json:"workflowInputs,omitempty"` // "KEY=value\nKEY2=value2"; supports templates
}

// Automation links a trigger to a list of actions. Snapshot holds the
// last-seen state used by the manager to detect deltas.
type Automation struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"projectId"`
	Name            string             `json:"name"`
	Enabled         bool               `json:"enabled"`
	Source          string             `json:"source"`
	Trigger         AutomationTrigger  `json:"trigger"`
	Actions         []AutomationAction `json:"actions"`
	PollIntervalSec int                `json:"pollIntervalSec"`
	SnapshotJSON    string             `json:"snapshotJson,omitempty"`
}

// AutomationRunOutcome describes whether the actions chain succeeded.
type AutomationRunOutcome string

const (
	RunOutcomeFired AutomationRunOutcome = "fired" // every action succeeded
	RunOutcomeError AutomationRunOutcome = "error" // at least one action errored
)

// ActionResult is one entry in AutomationRun.Actions, capturing how a single
// action of the automation chain played out.
type ActionResult struct {
	Kind   string `json:"kind"`
	Status string `json:"status"` // "ok" | "error" | "skipped"
	Detail string `json:"detail,omitempty"`
}

// AutomationRun is one row of the automations_runs audit log: a single fire
// event including which actions ran and what they returned. Persisted by
// the AutomationManager after each dispatched trigger match.
type AutomationRun struct {
	ID           string               `json:"id"`
	AutomationID string               `json:"automationId"`
	ProjectID    string               `json:"projectId"`
	StartedAt    int64                `json:"startedAt"`
	Outcome      AutomationRunOutcome `json:"outcome"`
	Reason       string               `json:"reason"`
	Actions      []ActionResult       `json:"actions"`
}

type Service struct {
	store           *Store
	runner          *Runner
	repositoryStore *repositorystore.Store
	ticketsStore    *ticketsstore.Store
	sentryStore     *sentrystore.Store
	dokployStore    *dokploystore.Store

	// resolveBinary locates an agent CLI's absolute path by kind. Wired from the
	// app layer (which owns PATH/extra-dir resolution) so the service can respawn
	// a CLI — e.g. resuming a finished opencode session — without that knowledge.
	resolveBinary func(kind string) string

	focusMu    sync.RWMutex
	appFocused bool
}

func NewService(store *Store) *Service {
	return &Service{store: store}
}

func (s *Service) WithBinaryResolver(fn func(kind string) string) *Service {
	s.resolveBinary = fn
	return s
}

func (s *Service) WithRepositoryStore(store *repositorystore.Store) *Service {
	s.repositoryStore = store
	return s
}

func (s *Service) WithTicketsStore(store *ticketsstore.Store) *Service {
	s.ticketsStore = store
	return s
}

func (s *Service) WithSentryStore(store *sentrystore.Store) *Service {
	s.sentryStore = store
	return s
}

func (s *Service) WithDokployStore(store *dokploystore.Store) *Service {
	s.dokployStore = store
	return s
}

func (s *Service) RepositoryStore() *repositorystore.Store { return s.repositoryStore }

func (s *Service) TicketsStore() *ticketsstore.Store { return s.ticketsStore }

func (s *Service) SentryStore() *sentrystore.Store { return s.sentryStore }

func (s *Service) DokployStore() *dokploystore.Store { return s.dokployStore }

func (s *Service) Store() *Store {
	return s.store
}

func (s *Service) ListProjects() ([]Project, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListProjects()
}

func (s *Service) UpsertProject(p Project) (Project, error) {
	if s.store == nil {
		return Project{}, errors.New("store not initialised")
	}
	return s.store.UpsertProject(p)
}

func (s *Service) DeleteProject(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteProject(id)
}

func (s *Service) ListAgents(projectID string) ([]Agent, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListAgents(projectID)
}

func (s *Service) UpsertAgent(a Agent) (Agent, error) {
	if s.store == nil {
		return Agent{}, errors.New("store not initialised")
	}
	return s.store.UpsertAgent(a)
}

func (s *Service) DeleteAgent(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	agent, _ := s.store.GetAgent(id)
	if agent != nil {
		s.RemoveAgentWorktree(agent)
	}
	if err := s.store.DeleteAgent(id); err != nil {
		return err
	}
	s.deleteAgentLog(id)
	return nil
}

func (s *Service) ArchiveAgent(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.PatchAgent(id, map[string]any{"status": "archived"})
}

func (s *Service) GetDashboardStats(kind, model string) (DashboardStats, error) {
	if s.store == nil {
		return DashboardStats{}, errors.New("store not initialised")
	}
	return s.store.GetDashboardStats(kind, model)
}

func (s *Service) ListNotifications() ([]Notification, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListNotifications()
}

func (s *Service) UpsertNotification(n Notification) (Notification, error) {
	if s.store == nil {
		return Notification{}, errors.New("store not initialised")
	}
	return s.store.UpsertNotification(n)
}

func (s *Service) DeleteNotification(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteNotification(id)
}

func (s *Service) ListCustomProviders() ([]CustomProvider, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListCustomProviders()
}

func (s *Service) GetCustomProvider(id string) (*CustomProvider, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.GetCustomProvider(id)
}

func (s *Service) GetAgentDefaultModels() (map[string]string, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.GetAgentDefaultModels()
}

func (s *Service) SetAgentDefaultModel(id, model string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.SetAgentDefaultModel(id, model)
}

// SetAgentModel switches an existing agent's model. claude-code reads it on the
// next resumed turn (see buildResumeCommand), so the change takes effect from
// the following message — and overrides any model an overload fallback picked.
func (s *Service) SetAgentModel(agentID, model string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.PatchAgent(agentID, map[string]any{"model": model})
}

func (s *Service) UpsertCustomProvider(p CustomProvider) (CustomProvider, error) {
	if s.store == nil {
		return CustomProvider{}, errors.New("store not initialised")
	}
	return s.store.UpsertCustomProvider(p)
}

func (s *Service) DeleteCustomProvider(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteCustomProvider(id)
}

func (s *Service) MarkNotificationRead(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.MarkNotificationRead(id)
}

func (s *Service) MarkAllNotificationsRead() error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.MarkAllNotificationsRead()
}

// NotifyInput is the producer-side payload accepted by Notify. The title is
// rendered from TitleTemplate + Vars at fire time so callers can re-use a
// templated string across many fires without manual sprintf.
type NotifyInput struct {
	ProjectID     string
	Type          NotificationType
	Severity      NotificationSeverity
	TitleTemplate string
	Vars          map[string]string
	Payload       map[string]any
}

// Notify is the single funnel for raising a notification. It applies the
// user's per-kind preferences before persisting, then dispatches an OS toast
// when both the OS channel is enabled and the user hasn't muted everything.
func (s *Service) Notify(in NotifyInput) (Notification, error) {
	if s.store == nil {
		return Notification{}, errors.New("store not initialised")
	}
	if in.Severity == "" {
		in.Severity = SeverityInfo
	}
	n := Notification{
		ProjectID: in.ProjectID,
		Type:      in.Type,
		Severity:  in.Severity,
		Title:     renderTemplate(in.TitleTemplate, in.Vars),
		Payload:   in.Payload,
		CreatedAt: time.Now().Unix(),
	}
	settings, _ := s.store.GetNotificationSettings()
	if !eventEnabled(settings.Events, n) {
		return Notification{}, nil
	}
	saved, err := s.store.UpsertNotification(n)
	if err != nil {
		return saved, err
	}
	if !settings.SilenceAll && settings.OSEnabled && !s.isAppFocused() {
		go dispatchOSNotification(saved, settings)
	}
	return saved, nil
}

func (s *Service) GetNotificationSettings() (NotificationSettings, error) {
	if s.store == nil {
		return DefaultNotificationSettings(), errors.New("store not initialised")
	}
	return s.store.GetNotificationSettings()
}

func (s *Service) UpdateNotificationSettings(in NotificationSettings) (NotificationSettings, error) {
	if s.store == nil {
		return NotificationSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateNotificationSettings(in)
}

func (s *Service) GetAppearanceSettings() (AppearanceSettings, error) {
	if s.store == nil {
		return DefaultAppearanceSettings(), errors.New("store not initialised")
	}
	return s.store.GetAppearanceSettings()
}

func (s *Service) UpdateAppearanceSettings(in AppearanceSettings) (AppearanceSettings, error) {
	if s.store == nil {
		return AppearanceSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateAppearanceSettings(in)
}

func (s *Service) GetShortcutsSettings() (ShortcutsSettings, error) {
	if s.store == nil {
		return DefaultShortcutsSettings(), errors.New("store not initialised")
	}
	return s.store.GetShortcutsSettings()
}

func (s *Service) UpdateShortcutsSettings(in ShortcutsSettings) (ShortcutsSettings, error) {
	if s.store == nil {
		return ShortcutsSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateShortcutsSettings(in)
}

func (s *Service) GetGeneralSettings() (GeneralSettings, error) {
	if s.store == nil {
		return DefaultGeneralSettings(), errors.New("store not initialised")
	}
	return s.store.GetGeneralSettings()
}

func (s *Service) UpdateGeneralSettings(in GeneralSettings) (GeneralSettings, error) {
	if s.store == nil {
		return GeneralSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateGeneralSettings(in)
}

// SetAppFocused records whether the app window is currently focused. Used to
// gate OS toast dispatching: the bell still updates while focused, but the
// native toast is suppressed since the user is already in the app.
func (s *Service) SetAppFocused(focused bool) {
	s.focusMu.Lock()
	s.appFocused = focused
	s.focusMu.Unlock()
}

func (s *Service) isAppFocused() bool {
	s.focusMu.RLock()
	defer s.focusMu.RUnlock()
	return s.appFocused
}

// eventEnabled answers "should this notification be surfaced?" against the
// user's per-category preferences.
func eventEnabled(flags NotificationEventFlags, n Notification) bool {
	switch n.Type {
	case NotifTypeAgent:
		event, _ := n.Payload["event"].(string)
		switch AgentEvent(event) {
		case AgentEventWaiting:
			return flags.Waiting
		case AgentEventCompleted:
			// Both successful and failed terminal states route through here;
			// failures are split out via severity.
			if n.Severity == SeverityError {
				return flags.Errored
			}
			return flags.Completed
		default:
			return true
		}
	case NotifTypeAutomation:
		return flags.Automation
	case NotifTypeUser:
		return flags.User
	default:
		return true
	}
}

func (s *Service) ListAutomations() ([]Automation, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListAutomations()
}

func (s *Service) UpsertAutomation(a Automation) (Automation, error) {
	if s.store == nil {
		return Automation{}, errors.New("store not initialised")
	}
	return s.store.UpsertAutomation(a)
}

func (s *Service) DeleteAutomation(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteAutomation(id)
}

func (s *Service) ListAutomationRuns(automationID string, limit int) ([]AutomationRun, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListAutomationRuns(automationID, limit)
}
