package polaris

import (
	"errors"
	"sync"
	"time"

	"github.com/KevinBonnoron/polaris/internal/store/ghstore"
	"github.com/KevinBonnoron/polaris/internal/store/jirastore"
)

// IntegrationConfig holds the per-plugin settings for a single integration
// connected to a project. The shape is intentionally untyped: each plugin owns
// its own schema (defined client-side in the integration catalog) and is
// responsible for validating its own fields.
type IntegrationConfig map[string]any

type Project struct {
	ID           string                       `json:"id"`
	Name         string                       `json:"name"`
	Color        string                       `json:"color"`
	Path         string                       `json:"path"`
	Logo         string                       `json:"logo"`
	Integrations map[string]IntegrationConfig `json:"integrations"`
	// IsolatedDefault is the project-level default for new agents: when true,
	// the runner spawns the agent into a fresh git worktree on a generated
	// branch; when false, the agent works on the current branch in place.
	IsolatedDefault bool `json:"isolatedDefault"`
	// BranchPrefix is the prefix prepended to auto-generated branch names
	// when IsolatedDefault is on (e.g. "polaris/", "feat/"). Used only for
	// manual spawns — automation triggers carry their own branch name.
	BranchPrefix string `json:"branchPrefix"`
	// HasGit is computed at read time from the project path. Not persisted —
	// reflects the live filesystem so it stays correct after `git init` or
	// directory moves without requiring a manual refresh.
	HasGit bool `json:"hasGit"`
}

type Agent struct {
	ID        string `json:"id"`
	ProjectID string `json:"projectId"`
	Kind      string `json:"kind"`
	// Summary is a short description of the agent's task, generated by the CLI
	// after the first turn (e.g. claude's `summary` of the user's request).
	// Empty until the first turn produces text.
	Summary   string `json:"summary"`
	Status    string `json:"status"`
	StartedAt int64  `json:"startedAt"`
	Tokens    int    `json:"tokens"`
	// Token breakdown across the agent's turns. Tokens stays the sum of these
	// four; they're surfaced so the UI can explain why a total is large (cache
	// re-reads of the fixed context dominate the actual new work).
	TokensInput       int    `json:"tokensInput"`
	TokensOutput      int    `json:"tokensOutput"`
	TokensCacheCreate int    `json:"tokensCacheCreate"`
	TokensCacheRead   int    `json:"tokensCacheRead"`
	SessionID         string `json:"sessionId"`
	// Source is "manual" (default) when the user spawned the agent from the
	// UI, or "automation" when an Automation rule triggered the run. Used to
	// suppress lifecycle notifications for manually-launched agents — the
	// user is already watching their own spawn.
	Source        string  `json:"source"`
	CostUSD       float64 `json:"costUsd"`
	FilesModified int     `json:"filesModified"`
	ToolsUsed     int     `json:"toolsUsed"`
	// Branch and WorktreePath are populated when the agent runs in an isolated
	// git worktree (currently: Jira-triggered automations). When empty, the
	// agent worked directly inside the project's root.
	Branch       string `json:"branch,omitempty"`
	WorktreePath string `json:"worktreePath,omitempty"`
	// IssueKey carries the originating ticket (e.g. "ABC-123") so the PR title
	// and follow-up actions can reference it.
	IssueKey string `json:"issueKey,omitempty"`
	// PRURL is set once CreatePRForAgent successfully opened a pull request.
	PRURL string `json:"prUrl,omitempty"`
	// Model is the CLI model chosen at spawn time. Needed for deferred-start
	// agents (created with empty task) so the first Send can pass it to the
	// initial spawn command.
	Model string `json:"model,omitempty"`
	// PendingQuestionID is the tool_use id of an unanswered AskUserQuestion
	// tool call. Persisted so the choices remain visible if the modal was
	// closed when the question fired, or if the app restarts mid-question.
	PendingQuestionID string `json:"pendingQuestionId,omitempty"`
	// PendingQuestionInput is the JSON-encoded tool input (the questions
	// payload) shown to the user. Empty when no question is pending.
	PendingQuestionInput string `json:"pendingQuestionInput,omitempty"`
}

type CustomProvider struct {
	ID       string   `json:"id"`
	Name     string   `json:"name"`
	Color    string   `json:"color"`
	Endpoint string   `json:"endpoint"`
	APIKey   string   `json:"apiKey"`
	APIType  string   `json:"apiType"`
	Models   []string `json:"models"`
}

// NotificationSeverity tags every notification with how concerning it is.
// The frontend uses it for tone/colour and (eventually) per-severity
// settings. Adding a value requires a matching entry in src/db/types.ts.
type NotificationSeverity string

const (
	SeverityInfo    NotificationSeverity = "info"
	SeveritySuccess NotificationSeverity = "success"
	SeverityWarning NotificationSeverity = "warning"
	SeverityError   NotificationSeverity = "error"
)

// NotificationType discriminates the source of the notification. Each value
// determines the shape of Payload (see Agent/Automation/User payload types).
type NotificationType string

const (
	NotifTypeAgent      NotificationType = "agent"
	NotifTypeAutomation NotificationType = "automation"
	NotifTypeUser       NotificationType = "user"
)

// AgentEvent narrows what happened on an agent-typed notification. Stored
// inside the agent payload, not at the top level, because automation/user
// notifications don't have an equivalent.
type AgentEvent string

const (
	AgentEventWaiting   AgentEvent = "waiting"
	AgentEventCompleted AgentEvent = "completed"
)

// AgentNotificationPayload is the JSON shape persisted in payloadJson when
// Type == NotifTypeAgent.
type AgentNotificationPayload struct {
	AgentID string     `json:"agentId"`
	Event   AgentEvent `json:"event"`
}

// AutomationNotificationPayload is the JSON shape persisted in payloadJson
// when Type == NotifTypeAutomation.
type AutomationNotificationPayload struct {
	AutomationID string `json:"automationId,omitempty"`
}

type Notification struct {
	ID        string               `json:"id"`
	ProjectID string               `json:"projectId"`
	Type      NotificationType     `json:"type"`
	Severity  NotificationSeverity `json:"severity"`
	Title     string               `json:"title"`
	Payload   map[string]any       `json:"payload,omitempty"`
	CreatedAt int64                `json:"createdAt"`
	Read      bool                 `json:"read"`
}

// AgentID is a convenience accessor for payload["agentId"] when Type=agent.
// Returns "" when the notification isn't agent-typed or the field is absent.
func (n Notification) AgentID() string {
	if n.Type != NotifTypeAgent || n.Payload == nil {
		return ""
	}
	if v, ok := n.Payload["agentId"].(string); ok {
		return v
	}
	return ""
}

// NotificationEventFlags toggles in-app and OS surfacing per category. A
// flag set to false drops the notification entirely (not persisted, no OS
// toast). The agent flags (Waiting/Completed/Errored/Started) gate
// agent-typed notifications by AgentEvent + severity; Automation and User
// gate everything emitted under their respective NotificationType.
type NotificationEventFlags struct {
	Waiting    bool `json:"waiting"`
	Completed  bool `json:"completed"`
	Errored    bool `json:"errored"`
	Started    bool `json:"started"`
	Automation bool `json:"automation"`
	User       bool `json:"user"`
}

// NotificationSettings is the user-tunable delivery policy applied at the
// service boundary before any notification is persisted or pushed to the OS.
type NotificationSettings struct {
	OSEnabled  bool                   `json:"osEnabled"`
	Sound      string                 `json:"sound"`
	SilenceAll bool                   `json:"silenceAll"`
	Events     NotificationEventFlags `json:"events"`
}

// DefaultNotificationSettings is what new installs see and what we fall back
// to when a row is missing or partially decoded.
func DefaultNotificationSettings() NotificationSettings {
	return NotificationSettings{
		OSEnabled:  true,
		Sound:      "default",
		SilenceAll: false,
		Events: NotificationEventFlags{
			Waiting:    true,
			Completed:  true,
			Errored:    true,
			Started:    false,
			Automation: true,
			User:       true,
		},
	}
}

type CustomTheme struct {
	Key    string            `json:"key"`
	Name   string            `json:"name"`
	Mode   string            `json:"mode"`
	Colors map[string]string `json:"colors"`
}

type AppearanceSettings struct {
	Theme         string        `json:"theme"`
	ThinkingStyle string        `json:"thinkingStyle"`
	CustomThemes  []CustomTheme `json:"customThemes"`
}

func DefaultAppearanceSettings() AppearanceSettings {
	return AppearanceSettings{
		Theme:         "classic-dark",
		ThinkingStyle: "dots",
		CustomThemes:  []CustomTheme{},
	}
}

type ShortcutBinding struct {
	Key  string `json:"key"`
	Meta bool   `json:"meta"`
}

type ShortcutsSettings struct {
	OpenPalette   ShortcutBinding `json:"openPalette"`
	SwitchProject ShortcutBinding `json:"switchProject"`
	AddProject    ShortcutBinding `json:"addProject"`
	NewAgent      ShortcutBinding `json:"newAgent"`
	ToggleSidebar ShortcutBinding `json:"toggleSidebar"`
	CloseModal    ShortcutBinding `json:"closeModal"`
}

func DefaultShortcutsSettings() ShortcutsSettings {
	return ShortcutsSettings{
		OpenPalette:   ShortcutBinding{Key: "k", Meta: true},
		SwitchProject: ShortcutBinding{Key: "p", Meta: true},
		AddProject:    ShortcutBinding{Key: "o", Meta: true},
		NewAgent:      ShortcutBinding{Key: "n", Meta: true},
		ToggleSidebar: ShortcutBinding{Key: "b", Meta: true},
		CloseModal:    ShortcutBinding{Key: "Escape", Meta: false},
	}
}

// GeneralSettings groups misc app-wide preferences that don't belong to a
// more specific category. When AutoResumeSessions is true, agents found in
// an in-flight state at startup (working/waiting) are auto-resumed with a
// neutral continuation prompt instead of being marked as errored.
type GeneralSettings struct {
	AutoResumeSessions bool `json:"autoResumeSessions"`
}

func DefaultGeneralSettings() GeneralSettings {
	return GeneralSettings{
		AutoResumeSessions: false,
	}
}

// AutomationTrigger is the discriminated payload describing what conditions
// fire an automation. The wire format is JSON so the frontend can evolve the
// shape without forcing a Go-side migration on every change.
type AutomationTrigger struct {
	// Kind is one of: "jira.transition", "repository.pr_opened".
	Kind string `json:"kind"`
	// FromStatusIDs is the set of source statuses accepted ([] = any). For
	// "jira.transition".
	FromStatusIDs []string `json:"fromStatusIds,omitempty"`
	// ToStatusID is the destination status (required for jira.transition).
	ToStatusID string `json:"toStatusId,omitempty"`
	// Assignee filter: "me" / "any" / specific displayName.
	Assignee string `json:"assignee,omitempty"`
	// AlsoOnReassignment fires even when the status didn't change, as long as
	// the assignee just became the configured one.
	AlsoOnReassignment bool `json:"alsoOnReassignment,omitempty"`
	// IncludeDrafts, when true, lets repository.pr_opened fire for draft PRs.
	IncludeDrafts bool `json:"includeDrafts,omitempty"`
	// AuthorFilter restricts repository.pr_opened to a specific GitHub login.
	// Empty means any author.
	AuthorFilter string `json:"authorFilter,omitempty"`
	// ExcludeOwnComments, when true, skips comments authored by the current
	// gh-authenticated user on repository.pr_comment triggers.
	ExcludeOwnComments bool `json:"excludeOwnComments,omitempty"`
	// OnlyMine restricts repository.pr_build_failed / pr_build_success to PRs
	// authored by the current gh-authenticated user, and
	// repository.issue_assigned to issues newly assigned to that user.
	OnlyMine bool `json:"onlyMine,omitempty"`
}

// AutomationAction is the discriminated payload describing one action to run
// when the trigger fires. Multiple actions execute in declaration order; a
// failing action only logs and does not halt the chain.
type AutomationAction struct {
	// Kind is one of: "spawn_agent", "jira_transition", "notification".
	Kind string `json:"kind"`

	// spawn_agent fields
	AgentKind    string `json:"agentKind,omitempty"`
	Model        string `json:"model,omitempty"`
	TaskTemplate string `json:"taskTemplate,omitempty"`

	// jira_transition fields. JiraIssueKey is a template (e.g. "{{key}}");
	// empty means "use the issue key from the trigger context", which for
	// repository triggers is auto-extracted from the branch or PR title.
	JiraIssueKey   string `json:"jiraIssueKey,omitempty"`
	JiraToStatusID string `json:"jiraToStatusId,omitempty"`

	// notification fields
	NotifyTitle string `json:"notifyTitle,omitempty"` // template
	NotifyKind  string `json:"notifyKind,omitempty"`  // "info" (default) | "warning" | "error"
}

// Automation links a trigger to a list of actions. Snapshot holds the
// last-seen state used by the manager to detect deltas.
type Automation struct {
	ID              string             `json:"id"`
	ProjectID       string             `json:"projectId"`
	Name            string             `json:"name"`
	Enabled         bool               `json:"enabled"`
	Source          string             `json:"source"`
	Trigger         AutomationTrigger  `json:"trigger"`
	Actions         []AutomationAction `json:"actions"`
	PollIntervalSec int                `json:"pollIntervalSec"`
	SnapshotJSON    string             `json:"snapshotJson,omitempty"`
}

// AutomationRunOutcome describes whether the actions chain succeeded.
type AutomationRunOutcome string

const (
	RunOutcomeFired AutomationRunOutcome = "fired" // every action succeeded
	RunOutcomeError AutomationRunOutcome = "error" // at least one action errored
)

// ActionResult is one entry in AutomationRun.Actions, capturing how a single
// action of the automation chain played out.
type ActionResult struct {
	Kind   string `json:"kind"`
	Status string `json:"status"` // "ok" | "error" | "skipped"
	Detail string `json:"detail,omitempty"`
}

// AutomationRun is one row of the automations_runs audit log: a single fire
// event including which actions ran and what they returned. Persisted by
// the AutomationManager after each dispatched trigger match.
type AutomationRun struct {
	ID           string               `json:"id"`
	AutomationID string               `json:"automationId"`
	ProjectID    string               `json:"projectId"`
	StartedAt    int64                `json:"startedAt"`
	Outcome      AutomationRunOutcome `json:"outcome"`
	Reason       string               `json:"reason"`
	Actions      []ActionResult       `json:"actions"`
}

type Service struct {
	store     *Store
	runner    *Runner
	ghStore   *ghstore.Store
	jiraStore *jirastore.Store

	focusMu    sync.RWMutex
	appFocused bool
}

func NewService(store *Store) *Service {
	return &Service{store: store}
}

func (s *Service) WithGhStore(store *ghstore.Store) *Service {
	s.ghStore = store
	return s
}

func (s *Service) WithJiraStore(store *jirastore.Store) *Service {
	s.jiraStore = store
	return s
}

func (s *Service) GhStore() *ghstore.Store { return s.ghStore }

func (s *Service) JiraStore() *jirastore.Store { return s.jiraStore }

func (s *Service) Store() *Store {
	return s.store
}

func (s *Service) ListProjects() ([]Project, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListProjects()
}

func (s *Service) UpsertProject(p Project) (Project, error) {
	if s.store == nil {
		return Project{}, errors.New("store not initialised")
	}
	return s.store.UpsertProject(p)
}

func (s *Service) DeleteProject(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteProject(id)
}

func (s *Service) ListAgents(projectID string) ([]Agent, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListAgents(projectID)
}

func (s *Service) UpsertAgent(a Agent) (Agent, error) {
	if s.store == nil {
		return Agent{}, errors.New("store not initialised")
	}
	return s.store.UpsertAgent(a)
}

func (s *Service) DeleteAgent(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	agent, _ := s.store.GetAgent(id)
	if agent != nil {
		s.RemoveAgentWorktree(agent)
	}
	return s.store.DeleteAgent(id)
}

func (s *Service) ListNotifications() ([]Notification, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListNotifications()
}

func (s *Service) UpsertNotification(n Notification) (Notification, error) {
	if s.store == nil {
		return Notification{}, errors.New("store not initialised")
	}
	return s.store.UpsertNotification(n)
}

func (s *Service) DeleteNotification(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteNotification(id)
}

func (s *Service) ListCustomProviders() ([]CustomProvider, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListCustomProviders()
}

func (s *Service) UpsertCustomProvider(p CustomProvider) (CustomProvider, error) {
	if s.store == nil {
		return CustomProvider{}, errors.New("store not initialised")
	}
	return s.store.UpsertCustomProvider(p)
}

func (s *Service) DeleteCustomProvider(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteCustomProvider(id)
}

func (s *Service) MarkNotificationRead(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.MarkNotificationRead(id)
}

func (s *Service) MarkAllNotificationsRead() error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.MarkAllNotificationsRead()
}

// NotifyInput is the producer-side payload accepted by Notify. The title is
// rendered from TitleTemplate + Vars at fire time so callers can re-use a
// templated string across many fires without manual sprintf.
type NotifyInput struct {
	ProjectID     string
	Type          NotificationType
	Severity      NotificationSeverity
	TitleTemplate string
	Vars          map[string]string
	Payload       map[string]any
}

// Notify is the single funnel for raising a notification. It applies the
// user's per-kind preferences before persisting, then dispatches an OS toast
// when both the OS channel is enabled and the user hasn't muted everything.
func (s *Service) Notify(in NotifyInput) (Notification, error) {
	if s.store == nil {
		return Notification{}, errors.New("store not initialised")
	}
	if in.Severity == "" {
		in.Severity = SeverityInfo
	}
	n := Notification{
		ProjectID: in.ProjectID,
		Type:      in.Type,
		Severity:  in.Severity,
		Title:     renderTemplate(in.TitleTemplate, in.Vars),
		Payload:   in.Payload,
		CreatedAt: time.Now().Unix(),
	}
	settings, _ := s.store.GetNotificationSettings()
	if !eventEnabled(settings.Events, n) {
		return Notification{}, nil
	}
	saved, err := s.store.UpsertNotification(n)
	if err != nil {
		return saved, err
	}
	if !settings.SilenceAll && settings.OSEnabled && !s.isAppFocused() {
		go dispatchOSNotification(saved, settings)
	}
	return saved, nil
}

func (s *Service) GetNotificationSettings() (NotificationSettings, error) {
	if s.store == nil {
		return DefaultNotificationSettings(), errors.New("store not initialised")
	}
	return s.store.GetNotificationSettings()
}

func (s *Service) UpdateNotificationSettings(in NotificationSettings) (NotificationSettings, error) {
	if s.store == nil {
		return NotificationSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateNotificationSettings(in)
}

func (s *Service) GetAppearanceSettings() (AppearanceSettings, error) {
	if s.store == nil {
		return DefaultAppearanceSettings(), errors.New("store not initialised")
	}
	return s.store.GetAppearanceSettings()
}

func (s *Service) UpdateAppearanceSettings(in AppearanceSettings) (AppearanceSettings, error) {
	if s.store == nil {
		return AppearanceSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateAppearanceSettings(in)
}

func (s *Service) GetShortcutsSettings() (ShortcutsSettings, error) {
	if s.store == nil {
		return DefaultShortcutsSettings(), errors.New("store not initialised")
	}
	return s.store.GetShortcutsSettings()
}

func (s *Service) UpdateShortcutsSettings(in ShortcutsSettings) (ShortcutsSettings, error) {
	if s.store == nil {
		return ShortcutsSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateShortcutsSettings(in)
}

func (s *Service) GetGeneralSettings() (GeneralSettings, error) {
	if s.store == nil {
		return DefaultGeneralSettings(), errors.New("store not initialised")
	}
	return s.store.GetGeneralSettings()
}

func (s *Service) UpdateGeneralSettings(in GeneralSettings) (GeneralSettings, error) {
	if s.store == nil {
		return GeneralSettings{}, errors.New("store not initialised")
	}
	return s.store.UpdateGeneralSettings(in)
}

// SetAppFocused records whether the app window is currently focused. Used to
// gate OS toast dispatching: the bell still updates while focused, but the
// native toast is suppressed since the user is already in the app.
func (s *Service) SetAppFocused(focused bool) {
	s.focusMu.Lock()
	s.appFocused = focused
	s.focusMu.Unlock()
}

func (s *Service) isAppFocused() bool {
	s.focusMu.RLock()
	defer s.focusMu.RUnlock()
	return s.appFocused
}

// eventEnabled answers "should this notification be surfaced?" against the
// user's per-category preferences.
func eventEnabled(flags NotificationEventFlags, n Notification) bool {
	switch n.Type {
	case NotifTypeAgent:
		event, _ := n.Payload["event"].(string)
		switch AgentEvent(event) {
		case AgentEventWaiting:
			return flags.Waiting
		case AgentEventCompleted:
			// Both successful and failed terminal states route through here;
			// failures are split out via severity.
			if n.Severity == SeverityError {
				return flags.Errored
			}
			return flags.Completed
		default:
			return true
		}
	case NotifTypeAutomation:
		return flags.Automation
	case NotifTypeUser:
		return flags.User
	default:
		return true
	}
}

func (s *Service) ListAutomations() ([]Automation, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListAutomations()
}

func (s *Service) UpsertAutomation(a Automation) (Automation, error) {
	if s.store == nil {
		return Automation{}, errors.New("store not initialised")
	}
	return s.store.UpsertAutomation(a)
}

func (s *Service) DeleteAutomation(id string) error {
	if s.store == nil {
		return errors.New("store not initialised")
	}
	return s.store.DeleteAutomation(id)
}

func (s *Service) ListAutomationRuns(automationID string, limit int) ([]AutomationRun, error) {
	if s.store == nil {
		return nil, errors.New("store not initialised")
	}
	return s.store.ListAutomationRuns(automationID, limit)
}
